### PR TITLE
Adding support for Telegram as a Notifier

### PR DESCRIPTION
**Pull request by stjohnjohnson**
👋 Thanks for this brilliant project.  Looking to add support for using [Telegram](https://core.telegram.org/) to notify on available campsites.

I've tested it locally and it works nice:
Screen Shot 2022-02-26 at 23 43 00

### CODE REVIEW

**Comment by juftin** [comment]
This is really neat! I've just gotten a chance to glance at the code but everything looks really great. I'll try to take a look and get this in soon

**Comment by stjohnjohnson** [comment]
Updated the version and fixed the lint errors in the files I touched.  Not sure if you want me to resolve the other files.

**Comment by juftin** [comment]
> Updated the version and fixed the lint errors in the files I touched. Not sure if you want me to resolve the other files.

No worries about resolving linting issues on other files - everything looks very clean on your end. I'm going to dig into the [failing docs job](https://github.com/juftin/camply/runs/5352168699?check_suite_focus=true) and get you approval on this later tonight. Thank you for the contributions @stjohnjohnson

**Comment by juftin** [comment]
This looks great 🙌 , I'm going to get it into a `0.3.0` branch and then into `main`- the `docs` GitHub action is currently dependent on a repository secret to run. I'll link the PR here.

**Comment by stjohnjohnson** [comment]
Brilliant!  Thanks for the merge.  What's the normal time for Docker images to be built?

**Pull request merged**
