### PR TITLE
Update documentation on how to specify multiple notification providers

### PR DESCRIPTION
**Pull request by septikus**
Click doesn't support comma-separated value for multiple options:
 https://click.palletsprojects.com/en/8.1.x/options/#multiple-options

When trying to use a comma-separated list of values for `--notifications`, camply crashes.

Also note that I haven't made many/any contributions via Github before, so if I'm not following best practices please educate me!

### CODE REVIEW

**Comment by juftin** [comment]
This is awesome @septikus. This is a very welcome documentation update.

GitHub will run some final unit tests and this will be good to go soon.

**Comment by juftin** [comment]
Ohhh.... I see what's going on. My original intention was to allow commas to work here: https://github.com/juftin/camply/blob/5c3e04fc3a96d08808b43ee41b0c558852580c8d/camply/notifications/multi_provider_notifications.py#L45-L46

We can fix this and keep the commas working as the documentation originally explains with this small edit:
```python
    def __init__(self, provider: Union[str, List[str], BaseNotifications, None]):
        """
        Initialize with a Notifier Class Object, a string or list of strings
        Parameters
        ----------
        provider: Union[str, List[str], BaseNotifications, None]
            Provider String, Comma Separated Provider String, or list of provider
            strings
        """
        self.providers = [SilentNotifications()]
        if isinstance(provider, str):
            provider = [prov_string.strip() for prov_string in provider.split(",")]
        elif isinstance(provider, list) and len(provider) == 1 and isinstance(provider[0], str):
            provider = [prov_string.strip() for prov_string in provider[0].split(",")]
       ...
```

The way that click works, instead of passing in a string with something like "slack, email", it passes in a list: `["slack, email"]`

**Comment by septikus** [comment]
Ah good to know!

When will `provider` ever be just a `str`? From reading through Click documentation, if an option has `multiple=True`, then the value of the option should always be a List or Tuple. 

ie. Is this line of code even necessary?
https://github.com/juftin/camply/blob/5c3e04fc3a96d08808b43ee41b0c558852580c8d/camply/notifications/multi_provider_notifications.py#L45-L46

I think the edit you proposed makes sense for handling the comma-separated case. It wouldn't handle someone trying to mix this. eg. `--notifications foo,bar --notifcations baz`, but that's quite the edge case.

Ultimately I'm fine either way: We could either not support comma-separation at all (since there are interesting edge cases) and potentially remove some code as well, or move towards support for it as you've proposed. 

My preference is to *not* support comma-separation, as it's currently not used (since it crashes `camply`) and adds slight overhead in edge case handling. I'm happy to make either change though.

**Comment by juftin** [comment]
My idea there was to keep the Python API easier easy to use - Click won't ever pass it in as a string. 

Let's go forward with your PR as is without removing that code. The CLI is much cleaner that way and we don't have all those edge cases. 

Thank you very much for the contribution!

**Pull request merged**
