### PR TITLE
✨ Add support for Ntfy notifications

### PR DESCRIPTION
**Pull request by ethan-leba**
See https://ntfy.sh

# Description

Adds support for ntfy.sh, which is extremely easy to set up! The other providers have a bit more friction or are paid.

# Has This Been Tested?

Tested manually!

# Checklist:

- [X] I've read the [contributing guidelines](https://juftin.com/camply/contributing) of this project
- [X] I've installed and used `.pre_commit` on all my code
- [X] I have documented my code, particularly in hard-to-understand areas
- [X] I have made any necessary corresponding changes to the documentation

### CODE REVIEW

**Comment by juftin** [comment]
Oh this is cool. Excited to try it out

**Review by juftin — APPROVED** [review]
Hey @ethan-leba I just added some small docs updates for this: https://github.com/juftin/camply/pull/248/commits/318b1616b45be2bd3af8e77e248019bc80f2e356

I tested this out successfully with 

```shell
camply test-notifications --notifications ntfy --debug
```

Side note, I'm a big fan of ntfy. I've never seen this before and it looks like it'll probably become my recommended notification solution. Thank you for the contribution and tip on this awesome service.

**Comment by ethan-leba** [comment]
> Hey @ethan-leba I just added some small docs updates for this: [318b161](https://github.com/juftin/camply/commit/318b1616b45be2bd3af8e77e248019bc80f2e356)
> 
> I tested this out successfully with
> 
> ```shell
> camply test-notifications --notifications ntfy --debug
> ```
> 
> Side note, I'm a big fan of ntfy. I've never seen this before and it looks like it'll probably become my recommended notification solution. Thank you for the contribution and tip on this awesome service.

Thanks for cleaning up the PR! And yeah, ntfy is great! I saw it on hacker news a couple months ago, its pretty perfect for personal notification use cases.

**Pull request merged**
