### PR TITLE
:sparkles: Add support for Apprise notifications

### PR DESCRIPTION
**Pull request by BHSPitMonkey**
# Description

[//]: # (Please include a summary of the changes and a link/description of the related issue.)
[//]: # (Please also include relevant motivation and context.)

This PR adds [Apprise](https://github.com/caronc/apprise) as a supported notification provider.

Apprise is a popular Python library that exposes the ability to notify using dozens of popular notification and messaging services (and protocols), including Discord, Home Assistant, and MQTT.

Users configure Apprise by specifying a URL which contains details of the service being used and any relevant authentication tokens. Some examples borrowed from their documentation:

- Discord: `discord://webhook_id/webhook_token`
- Home Assistant: `hassio://hostname/accesstoken`
- MQTT: `mqtt://user@hostname/topic`

# Has This Been Tested?

I've tested this locally using:

```
camply test-notifications --notifications apprise 
```

after configuring a `APPRISE_URL` in my `.camply` file (using the interactive configurator).

Apprise URLs take many forms depending on the notification service being used.
Refer to the [documentation](https://github.com/caronc/apprise#productivity-based-notifications) for supported schemes and examples.

# Checklist:

- [x] I've read the [contributing guidelines](https://juftin.com/camply/contributing) of this project
- [x] I've installed and used `.pre_commit` on all my code
- [x] I have documented my code, particularly in hard-to-understand areas
- [x] I have made any necessary corresponding changes to the documentation

### CODE REVIEW

**Comment by BHSPitMonkey** [comment]
Some additional comments:

- I wasn't sure if adding the new package via `[project.optional-dependencies]` was the correct call here, but I figured it was safe to follow the example set by the Twilio notifier. Please let me know if there's a better way to go (or change at will)!
- This is my first time working with `hatch`; Apologies if I've missed a step relating to the addition of the new package.

**Comment by juftin** [comment]
Nice, this looks very solid. Apprise seems like it'll fit a ton of different notification use cases. I will get a closer look at it later to make sure all the hatch stuff is set up right and the tests are passing. Thank you for the contribution 🏕️

**Comment by juftin** [comment]
Hey @BHSPitMonkey, hope you don't mind, I squashed your commits into one, and then added a couple commits to resolve the issues. I'm new to hatch as well so it took me a sec.

Changes Made
- Default the environment to `Python 3.9` This adds some dependencies that more recent of Python don't need
- Freeze The Unit tests in Time
    - There were some unit tests that broke after May 1st due to some time-based limitations. To prevent this from happening to all of the unit tests I did some time traveling using freezegun.

**Review by juftin — APPROVED** [review]
Okay, apologies again for some of the commit craziness going on. I tweaked the docs slightly and resolved all the issues. This is ready for primetime. I tested successfully with pushover via apprise too. 

Thank you again for the contribution, this is truly awesome.

**Comment by BHSPitMonkey** [comment]
Apologies for what? Easiest time I've had landing a change in a long time :wink: Thanks for the help!

**Pull request merged**
